apiVersion: v1
kind: Service
metadata:
  name: ai-k8s-chat-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ai-k8s-chat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 30080 # Optionally specify a port
